# For possible values, see: https://github.com/k8s-at-home/library-charts/tree/common-4.0.1/charts/stable/common
#
# Values here have different tiers, with lower tiers taking precedence:
#   0. User-defined values (when instantiating the helm chart)
#   1. Chart defaults
#   2. Template defaults
#   3. Common library overrides
#   4. Common library defaults (defined at the link above)


# Chart defaults (Tier 1)
#
# These are default values for the chart that always apply
# unless explicitly overridden by the user (Tier 0)

image:
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent


# Template defaults (Tier 2)
#
# These are default values for the chart that apply only when certain keys are present.
# For example, this auto-enables any service/port that is defined in Tier 1/0, as well
# as setting default port numbers for common ports.
#
# Keys defined here are applied recursively to any values defined by Tier 1/0. Defaults are applied
# to the value if the key here is a whole-word regular expression match for the key being tested.
#
# If multiple values are present via a list, then they are applied in order. The current definition
# defines a default for services matching `^.*$` (every service), and then overrides those defaults
# specifically for a service matching `^main$`. Keys with higher precedence should appear earlier
# in the list.
#
# If multiple values are present via a map, they are applied in a non-deterministic order. This should
# only be used if the regex keys are mutually exclusive.
#
# These values ONLY apply when the parent key is defined in Tier 1/0. If a specific key should always
# be set unless overridden, it MUST be put in Tier 1/3 (depending on the purpose of the value).

defaults:
  service:
    - main:
        ports:
          http:
            port: 80
            protocol: HTTP
          metrics:
            port: 9090
    - .*:
        enabled: true
        ports:
          .*:
            enabled: true
            protocol: TCP
  persistence:
    .*:
      enabled: true
  configmap:
    .*:
      enabled: true


# Common library overrides (Tier 3)
# This disables some items that are enabled by default so that they conform to similar patterns used throughout
# the chart. For example, this disables implicitly enabled services so that the user does not need to do so
# (however, is the user defines the service, it will be enabled by the template defaults).

common:
  service:
    main:
      enabled: false
      ports:
        http:
          enabled: false
